name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/telemetry-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy telemetry-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/telemetry-api \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
